feature/add-versioning:  DEV-70290 : Adding '<platform>/<version>' as…
logicmonitor/lm-logs-azure pull request #17
Opened 2021-03-04 10:34 UTC by choudharypooja

… user-agent header in request to log-ingest-api

2021-03-04 11:37 UTC, pmelkowski requested changes
The user-agent shouldn't be configurable, but rather generated from the project name and version.

2021-03-05 10:01 UTC, pmelkowski commented on build.gradle
> +}
please move this block just above `jar.dependsOn test`

2021-03-05 11:54 UTC, pmelkowski approved these changes
looks fine

2021-03-08 09:33 UTC, evancetesha approved these changes

2021-03-08 13:37 UTC, merged