Add mandatory metadata in LogEntry if exists.
logicmonitor/lm-logs-azure pull request #42
Opened 2023-04-05 08:27 UTC by siddharthck

Add static metadata _integration : azure .
Add event metadata for following keys :
level -> severity, operationName -> activity_type, resourceId -> azure_resource_id, category -> category .

2023-04-20 10:34 UTC, siddharthck commented on build.gradle
> +    implementation 'com.jayway.jsonpath:json-path:2.5.0'
We are already using jayway jsonpath library in many internal projects. It has Apache 2 license. : 
https://github.com/json-path/JsonPath

2023-04-20 11:29 UTC, choudharypooja commented
Please add the local.settings.json file as well

2023-04-20 12:57 UTC, vishaalcharpe approved these changes
Looks good to me!

2023-04-20 12:59 UTC, choudharypooja requested changes
local.settings.json missing still i guess

2023-04-20 13:03 UTC, vishaalcharpe requested changes
Please handle changes mentioned by Pooja

2023-04-20 13:13 UTC, choudharypooja approved these changes

2023-04-20 13:13 UTC, choudharypooja commented
LGTM

2023-04-20 15:43 UTC, mukundneharkar approved these changes

2023-04-21 04:48 UTC, merged

2023-04-21 07:09 UTC, vishaalcharpe reviewed
Approved!