Dev 136633 bearer token support
logicmonitor/lm-logs-azure pull request #46
Opened 2023-07-06 12:10 UTC by siddharthck

2023-07-06 12:51 UTC, ashishkucheria requested changes

2023-07-06 12:51 UTC, ashishkucheria commented on arm-template-deployment/deployRGParent.json
> +        "description": "If specified, make sure you also specify LM_Access_Key."
The description should be about LM_Access_Id

2023-07-06 12:51 UTC, ashishkucheria commented on arm-template-deployment/deployRGParent.json
> +        "description": "If specified, make sure you also specify LM_Access_Id."
The description should be about LM_Access_Key"

2023-07-07 04:37 UTC, choudharypooja commented on src/main/java/com/logicmonitor/logs/azure/LogEventForwarder.java
Should we add validation in the code as well? Like if all are missing we can log an error here as well.
Because the customer can change the configuration manually even after deploying the function app

2023-07-13 07:20 UTC, siddharthck commented
Will squash commits before merging.

2023-07-13 09:20 UTC, choudharypooja approved these changes
LGTM

2023-07-13 09:27 UTC, ashishkucheria approved these changes

2023-07-13 09:44 UTC, merged