DEVTS-17216 | Gson exception handling
logicmonitor/lm-logs-azure pull request #60
Opened 2024-01-24 05:23 UTC by ankit-gautam23

As part of DEVTS-17216, RCA done and added some code to it. Gson Error Exception Handled, Added some test to support that.

2024-01-24 06:24 UTC, ashishkucheria requested changes

2024-01-24 06:24 UTC, ashishkucheria commented on src/main/java/com/logicmonitor/logs/azure/LogEventAdapter.java
> +        try{
Comments should be removed.

2024-01-24 06:24 UTC, ashishkucheria commented on src/main/java/com/logicmonitor/logs/azure/LogEventForwarder.java
> +        }
formatting not proper.

2024-01-24 06:24 UTC, ashishkucheria commented on src/main/java/com/logicmonitor/logs/azure/LogEventAdapter.java
> +                System.out.println("Before reflat");
remove sysout.

2024-01-24 06:25 UTC, ankit-gautam23 commented on src/main/java/com/logicmonitor/logs/azure/LogEventAdapter.java
> +        try{
Sure, Will remove them.

2024-02-02 05:45 UTC, siddharthck commented on src/main/java/com/logicmonitor/logs/azure/LogEventForwarder.java
> +import java.util.*;
Do not import everyting with "*". Use specific imports

2024-02-02 11:24 UTC, siddharthck commented on src/main/java/com/logicmonitor/logs/azure/LogEventAdapter.java
> +import com.google.gson.*;
Do we need all the modules : import com.google.gson.*; ?

2024-02-02 11:26 UTC, siddharthck commented on src/main/java/com/logicmonitor/logs/azure/LogEventAdapter.java
> +    static {
Same code is present at two different locations. It would be better if we could reuse this code. So move this code to a different class ?

2024-02-02 11:31 UTC, ankit-gautam23 commented on src/main/java/com/logicmonitor/logs/azure/LogEventAdapter.java
>  import java.util.Map.Entry;
Done

2024-02-02 11:31 UTC, ankit-gautam23 commented on src/main/java/com/logicmonitor/logs/azure/LogEventForwarder.java
> +import java.util.*;
Done

2024-02-02 11:32 UTC, siddharthck commented on src/main/java/com/logicmonitor/logs/azure/LogEventForwarder.java
> +            log(DEFAULT_LOG_LEVEL, "Error while processing Json: " + e.getMessage());
Try using the exact LOG_LEVEL like Warning/Severe directly. Because, in future if default log level changed to INFO, we would log JsonSyntaxException as Info log.

2024-02-02 12:45 UTC, siddharthck commented
@ankit-gautam23 , I see that in individual commits, artefact file "lm-logs-azure.zip" is not updated. Please do build before you commit any changes. Also, try to squash the number of commits together. Right now PR has 12 Commits. As this is public facing github repo, we might not need to add internal jira-ticket number in commit messages.

2024-02-02 12:54 UTC, siddharthck commented
Please resolve conflicts.

2024-02-02 14:46 UTC, ankit-gautam23 commented on src/main/java/com/logicmonitor/logs/azure/LogEventAdapter.java
> +import com.google.gson.*;
Done

2024-02-06 04:41 UTC, ankit-gautam23 commented
@siddharthck @choudharypooja, changes are done and conflicts are resolved. Please have a look.

2024-02-06 05:20 UTC, siddharthck commented
@ankit-gautam23 , please bump up the version in build.gradle

2024-02-06 15:18 UTC, merged